package qurator.testcircuits

object Grover6{
    val qasm = 
        """
        OPENQASM 3.0;
        include "stdgates.inc";
        gate mcphase(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5 {
        h _gate_q_5;
        p(pi/8) _gate_q_0;
        p(pi/8) _gate_q_1;
        p(pi/8) _gate_q_2;
        p(pi/8) _gate_q_5;
        cx _gate_q_0, _gate_q_1;
        p(-pi/8) _gate_q_1;
        cx _gate_q_0, _gate_q_1;
        cx _gate_q_1, _gate_q_2;
        p(-pi/8) _gate_q_2;
        cx _gate_q_0, _gate_q_2;
        p(pi/8) _gate_q_2;
        cx _gate_q_1, _gate_q_2;
        p(-pi/8) _gate_q_2;
        cx _gate_q_0, _gate_q_2;
        cx _gate_q_2, _gate_q_5;
        p(-pi/8) _gate_q_5;
        cx _gate_q_1, _gate_q_5;
        p(pi/8) _gate_q_5;
        cx _gate_q_2, _gate_q_5;
        p(-pi/8) _gate_q_5;
        cx _gate_q_0, _gate_q_5;
        p(pi/8) _gate_q_5;
        cx _gate_q_2, _gate_q_5;
        p(-pi/8) _gate_q_5;
        cx _gate_q_1, _gate_q_5;
        p(pi/8) _gate_q_5;
        cx _gate_q_2, _gate_q_5;
        p(-pi/8) _gate_q_5;
        cx _gate_q_0, _gate_q_5;
        h _gate_q_5;
        rz(-pi/4) _gate_q_5;
        h _gate_q_5;
        cx _gate_q_4, _gate_q_5;
        tdg _gate_q_5;
        cx _gate_q_3, _gate_q_5;
        t _gate_q_5;
        cx _gate_q_4, _gate_q_5;
        tdg _gate_q_5;
        cx _gate_q_3, _gate_q_5;
        t _gate_q_4;
        t _gate_q_5;
        h _gate_q_5;
        cx _gate_q_3, _gate_q_4;
        t _gate_q_3;
        tdg _gate_q_4;
        cx _gate_q_3, _gate_q_4;
        rz(pi/4) _gate_q_5;
        h _gate_q_5;
        p(pi/8) _gate_q_0;
        p(pi/8) _gate_q_1;
        p(pi/8) _gate_q_2;
        p(pi/8) _gate_q_5;
        cx _gate_q_0, _gate_q_1;
        p(-pi/8) _gate_q_1;
        cx _gate_q_0, _gate_q_1;
        cx _gate_q_1, _gate_q_2;
        p(-pi/8) _gate_q_2;
        cx _gate_q_0, _gate_q_2;
        p(pi/8) _gate_q_2;
        cx _gate_q_1, _gate_q_2;
        p(-pi/8) _gate_q_2;
        cx _gate_q_0, _gate_q_2;
        cx _gate_q_2, _gate_q_5;
        p(-pi/8) _gate_q_5;
        cx _gate_q_1, _gate_q_5;
        p(pi/8) _gate_q_5;
        cx _gate_q_2, _gate_q_5;
        p(-pi/8) _gate_q_5;
        cx _gate_q_0, _gate_q_5;
        p(pi/8) _gate_q_5;
        cx _gate_q_2, _gate_q_5;
        p(-pi/8) _gate_q_5;
        cx _gate_q_1, _gate_q_5;
        p(pi/8) _gate_q_5;
        cx _gate_q_2, _gate_q_5;
        p(-pi/8) _gate_q_5;
        cx _gate_q_0, _gate_q_5;
        h _gate_q_5;
        rz(-pi/4) _gate_q_5;
        h _gate_q_5;
        cx _gate_q_4, _gate_q_5;
        tdg _gate_q_5;
        cx _gate_q_3, _gate_q_5;
        t _gate_q_5;
        cx _gate_q_4, _gate_q_5;
        tdg _gate_q_5;
        cx _gate_q_3, _gate_q_5;
        t _gate_q_4;
        t _gate_q_5;
        h _gate_q_5;
        cx _gate_q_3, _gate_q_4;
        t _gate_q_3;
        tdg _gate_q_4;
        cx _gate_q_3, _gate_q_4;
        rz(pi/4) _gate_q_5;
        h _gate_q_4;
        cx _gate_q_1, _gate_q_4;
        tdg _gate_q_4;
        cx _gate_q_0, _gate_q_4;
        t _gate_q_4;
        cx _gate_q_1, _gate_q_4;
        tdg _gate_q_4;
        cx _gate_q_0, _gate_q_4;
        t _gate_q_1;
        t _gate_q_4;
        h _gate_q_4;
        cx _gate_q_0, _gate_q_1;
        t _gate_q_0;
        tdg _gate_q_1;
        cx _gate_q_0, _gate_q_1;
        rz(-pi/8) _gate_q_4;
        h _gate_q_4;
        cx _gate_q_3, _gate_q_4;
        tdg _gate_q_4;
        cx _gate_q_2, _gate_q_4;
        t _gate_q_4;
        cx _gate_q_3, _gate_q_4;
        tdg _gate_q_4;
        cx _gate_q_2, _gate_q_4;
        t _gate_q_3;
        t _gate_q_4;
        h _gate_q_4;
        cx _gate_q_2, _gate_q_3;
        t _gate_q_2;
        tdg _gate_q_3;
        cx _gate_q_2, _gate_q_3;
        rz(pi/8) _gate_q_4;
        h _gate_q_4;
        cx _gate_q_1, _gate_q_4;
        tdg _gate_q_4;
        cx _gate_q_0, _gate_q_4;
        t _gate_q_4;
        cx _gate_q_1, _gate_q_4;
        tdg _gate_q_4;
        cx _gate_q_0, _gate_q_4;
        t _gate_q_1;
        t _gate_q_4;
        h _gate_q_4;
        cx _gate_q_0, _gate_q_1;
        t _gate_q_0;
        tdg _gate_q_1;
        cx _gate_q_0, _gate_q_1;
        rz(-pi/8) _gate_q_4;
        h _gate_q_4;
        cx _gate_q_3, _gate_q_4;
        tdg _gate_q_4;
        cx _gate_q_2, _gate_q_4;
        t _gate_q_4;
        cx _gate_q_3, _gate_q_4;
        tdg _gate_q_4;
        cx _gate_q_2, _gate_q_4;
        t _gate_q_3;
        t _gate_q_4;
        h _gate_q_4;
        cx _gate_q_2, _gate_q_3;
        t _gate_q_2;
        tdg _gate_q_3;
        cx _gate_q_2, _gate_q_3;
        rz(pi/8) _gate_q_4;
        h _gate_q_3;
        cx _gate_q_1, _gate_q_3;
        tdg _gate_q_3;
        cx _gate_q_0, _gate_q_3;
        t _gate_q_3;
        cx _gate_q_1, _gate_q_3;
        tdg _gate_q_3;
        cx _gate_q_0, _gate_q_3;
        t _gate_q_1;
        t _gate_q_3;
        h _gate_q_3;
        cx _gate_q_0, _gate_q_1;
        t _gate_q_0;
        tdg _gate_q_1;
        cx _gate_q_0, _gate_q_1;
        rz(-pi/16) _gate_q_3;
        cx _gate_q_2, _gate_q_3;
        rz(pi/16) _gate_q_3;
        h _gate_q_3;
        cx _gate_q_1, _gate_q_3;
        tdg _gate_q_3;
        cx _gate_q_0, _gate_q_3;
        t _gate_q_3;
        cx _gate_q_1, _gate_q_3;
        tdg _gate_q_3;
        cx _gate_q_0, _gate_q_3;
        t _gate_q_1;
        t _gate_q_3;
        h _gate_q_3;
        cx _gate_q_0, _gate_q_1;
        t _gate_q_0;
        tdg _gate_q_1;
        cx _gate_q_0, _gate_q_1;
        rz(-pi/16) _gate_q_3;
        cx _gate_q_2, _gate_q_3;
        rz(pi/16) _gate_q_3;
        cx _gate_q_0, _gate_q_2;
        rz(-pi/32) _gate_q_2;
        cx _gate_q_1, _gate_q_2;
        rz(pi/32) _gate_q_2;
        cx _gate_q_0, _gate_q_2;
        rz(-pi/32) _gate_q_2;
        cx _gate_q_1, _gate_q_2;
        rz(pi/32) _gate_q_2;
        crz(pi/16) _gate_q_0, _gate_q_1;
        p(pi/32) _gate_q_0;
        }
        gate mcx _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5 {
        h _gate_q_5;
        mcphase _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5;
        h _gate_q_5;
        }
        gate mcmt _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5 {
        h _gate_q_5;
        mcx _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5;
        h _gate_q_5;
        }
        bit[6] meas;
        qubit[6] q;
        x q[1];
        x q[2];
        mcmt q[0], q[1], q[2], q[3], q[4], q[5];
        x q[1];
        x q[2];
        h q[0];
        h q[1];
        h q[2];
        h q[3];
        h q[4];
        h q[5];
        x q[0];
        x q[1];
        x q[2];
        x q[3];
        x q[4];
        x q[5];
        h q[5];
        mcx q[0], q[1], q[2], q[3], q[4], q[5];
        h q[5];
        x q[0];
        x q[1];
        x q[2];
        x q[3];
        x q[4];
        x q[5];
        h q[0];
        h q[1];
        h q[2];
        h q[3];
        h q[4];
        h q[5];
        barrier q[0], q[1], q[2], q[3], q[4], q[5];
        meas[0] = measure q[0];
        meas[1] = measure q[1];
        meas[2] = measure q[2];
        meas[3] = measure q[3];
        meas[4] = measure q[4];
        meas[5] = measure q[5];
        """
}